required: sudo
services:
  - docker

before_install:
  - docker build -t subodh15/multitest -f ./client/Dockerfile.dev ./client

scripts:
  - docker run subodh15/multitest -e CI=true npm test

after_success:
  - docker build -t subodh15/multi-client ./client
  - docker build -t subodh15/multi-nginx ./nginx
  - docker build -t subodh15/multi-server ./server
  - docker build -t subodh15/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push subodh15/multi-client
  - docker push subodh15/multi-nginx
  - docker push subodh15/multi-server
  - docker push subodh15/multi-worker
  